project:
  type: website
  output-dir: _site

website:
  title: "Pooja Sukhdeve"
  navbar:
    right:
      - text: "About"
        href: index.qmd#about
      - text: "Skills"
        href: index.qmd#skills
      - text: "Projects"
        href: index.qmd#projects
      - text: "Services"
        href: index.qmd#services
      - text: "Contact"
        href: index.qmd#contact
format:
  html:
    theme: cosmo # or another simple Bootstrap theme
    css: styles.css # Add your custom styles if needed




